# Site settings
title: Arcadia
email: hello@seemplr.com
description: A public open-source infrastructure for the creation, visualisation and control by users of data–driven knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arcadia.network" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/in-dato-veritas
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: http://arcadnet.slack.com
twitter_url:
telegram_url: https://t.me/joinchat/C8XhMQxEGhSGBrvQT0hW2A

# Build settings
markdown: kramdown
